# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-14 16:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Cancellation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Check_In',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Check_Out',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('series_base', models.BooleanField(default=False)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruleString', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Suspended',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(auto_now=True)),
                ('end', models.DateTimeField(null=True)),
                ('qty', models.IntegerField(default=1)),
                ('desc', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Terminated',
            fields=[
                ('actor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='scheduling.Actor')),
                ('dt', models.DateTimeField(auto_now=True)),
                ('qty', models.IntegerField(default=1)),
                ('desc', models.TextField(null=True)),
            ],
            bases=('scheduling.actor',),
        ),
        migrations.CreateModel(
            name='Unavailable',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='scheduling.Event')),
                ('reason', models.TextField()),
            ],
            bases=('scheduling.event',),
        ),
        migrations.AddField(
            model_name='suspended',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.Actor'),
        ),
        migrations.AddField(
            model_name='event',
            name='series',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduling.Series'),
        ),
        migrations.AddField(
            model_name='check_out',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.Actor'),
        ),
        migrations.AddField(
            model_name='check_out',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.Event'),
        ),
        migrations.AddField(
            model_name='check_in',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.Actor'),
        ),
        migrations.AddField(
            model_name='check_in',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.Event'),
        ),
        migrations.AddField(
            model_name='cancellation',
            name='by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.Actor'),
        ),
        migrations.AddField(
            model_name='cancellation',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.Event'),
        ),
        migrations.AddField(
            model_name='attendee',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.Actor'),
        ),
        migrations.AddField(
            model_name='attendee',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.Event'),
        ),
    ]
