# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-14 16:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guide', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0001_initial'),
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signature',
            name='waiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.Waiver'),
        ),
        migrations.AddField(
            model_name='share',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Cart'),
        ),
        migrations.AddField(
            model_name='share',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Person'),
        ),
        migrations.AddField(
            model_name='resource_choice',
            name='choice_pool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.Choice_Pool'),
        ),
        migrations.AddField(
            model_name='resource_choice',
            name='ind_resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.Ind_Resource'),
        ),
        migrations.AddField(
            model_name='resource_choice',
            name='line_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Line_Item'),
        ),
        migrations.AddField(
            model_name='resource_allocation',
            name='ind_resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.Ind_Resource'),
        ),
        migrations.AddField(
            model_name='resource_allocation',
            name='line_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Line_Item'),
        ),
        migrations.AddField(
            model_name='resource_allocation',
            name='requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.Requirement'),
        ),
        migrations.AddField(
            model_name='refund',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Payment'),
        ),
        migrations.AddField(
            model_name='rebook',
            name='cause',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.Cause'),
        ),
        migrations.AddField(
            model_name='rebook',
            name='new_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='new', to='customer.Line_Item'),
        ),
        migrations.AddField(
            model_name='rebook',
            name='old_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='old', to='customer.Line_Item'),
        ),
        migrations.AddField(
            model_name='pricepoint',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Line_Item'),
        ),
        migrations.AddField(
            model_name='pricepoint',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.Price'),
        ),
        migrations.AddField(
            model_name='person',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='guide.Address'),
        ),
        migrations.AddField(
            model_name='payment',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Cart'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Payee'),
        ),
        migrations.AddField(
            model_name='line_item',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Cart'),
        ),
        migrations.AddField(
            model_name='hold',
            name='by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.Guide'),
        ),
        migrations.AddField(
            model_name='hold',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Cart'),
        ),
        migrations.AddField(
            model_name='guide_resource_addition',
            name='ind_resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.Ind_Resource'),
        ),
        migrations.AddField(
            model_name='guide_resource_addition',
            name='line_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Line_Item'),
        ),
        migrations.AddField(
            model_name='guide_note',
            name='line_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Line_Item'),
        ),
        migrations.AddField(
            model_name='guide_assignment',
            name='guide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.Guide'),
        ),
        migrations.AddField(
            model_name='guide_assignment',
            name='line_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Line_Item'),
        ),
        migrations.AddField(
            model_name='guide_assignment',
            name='requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.Requirement'),
        ),
        migrations.AddField(
            model_name='guardian_signature',
            name='guardian_signature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Signature'),
        ),
        migrations.AddField(
            model_name='guardian_signature',
            name='minor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minor', to='customer.Person'),
        ),
        migrations.AddField(
            model_name='group_resource_addition',
            name='ind_resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.Ind_Resource'),
        ),
        migrations.AddField(
            model_name='group_resource_addition',
            name='line_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Line_Item'),
        ),
        migrations.AddField(
            model_name='discount_code',
            name='items',
            field=models.ManyToManyField(blank=True, to='guide.Experience'),
        ),
        migrations.AddField(
            model_name='customer_note',
            name='by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.Guide'),
        ),
        migrations.AddField(
            model_name='customer_note',
            name='line_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Line_Item'),
        ),
        migrations.AddField(
            model_name='choice',
            name='choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.Answer_Choice'),
        ),
        migrations.AddField(
            model_name='choice',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Line_Item'),
        ),
        migrations.AddField(
            model_name='cancellation',
            name='cause',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.Cause'),
        ),
        migrations.AddField(
            model_name='cancellation',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customer.Line_Item'),
        ),
        migrations.AddField(
            model_name='applied_discount',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Cart'),
        ),
        migrations.AddField(
            model_name='answer',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Line_Item'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.Experience_Question'),
        ),
        migrations.AddField(
            model_name='resource_choice',
            name='party_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Party_Member'),
        ),
        migrations.AddField(
            model_name='product_experience',
            name='event',
            field=models.ManyToManyField(to='scheduling.Event'),
        ),
        migrations.AddField(
            model_name='product_experience',
            name='experience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.Experience'),
        ),
        migrations.AddField(
            model_name='payee',
            name='customer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.Customer'),
        ),
        migrations.AddField(
            model_name='party_member_choice',
            name='party_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Party_Member'),
        ),
        migrations.AddField(
            model_name='party_member_answer',
            name='party_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Party_Member'),
        ),
        migrations.AddField(
            model_name='party_member',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Cart'),
        ),
        migrations.AddField(
            model_name='manual_discount',
            name='guide',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='guide.Guide'),
        ),
        migrations.AddField(
            model_name='guide_note',
            name='by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer'),
        ),
        migrations.AddField(
            model_name='customer_choice',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer'),
        ),
        migrations.AddField(
            model_name='customer_answer',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer'),
        ),
        migrations.AddField(
            model_name='customer',
            name='actor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='scheduling.Actor'),
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cash_refund',
            name='guide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.Guide'),
        ),
        migrations.AddField(
            model_name='cash_payment',
            name='guide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.Guide'),
        ),
        migrations.AddField(
            model_name='cart',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer'),
        ),
        migrations.AddField(
            model_name='automatic_discount',
            name='code',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='customer.Discount_Code'),
        ),
    ]
